### ISSUE TITLE
Black line length

### ISSUE THREAD

**Issue by altendky** [pytest-dev/pytest-twisted#33]
Black defaults to a line length of 88 and reformats some stuff because of that.  Shall we configure it to 79?

`pyproject.toml`:
```toml
[tool.black]
line-length = 79
```
